#!/usr/bin/python
import sqlite3
conn = sqlite3.connect('shodan.db')

c = conn.cursor()

# Create table for query results
c.execute('''CREATE TABLE Query_Results
             (IP text,protocol text)''')

#TODO 
'''
Figure out the best method to parse the output from Shodan queries and store them
in an sqlite database. BeautifulSoup may be something to look into.
'''


conn.commit() #commiting changes to the database.
